{{- $useNetworkingV1 := .Capabilities.APIVersions.Has "networking.k8s.io/v1" -}}
{{- if .Values.collector.ingress.enabled -}}
{{- $servicePort := .Values.collector.service.http.port -}}
{{- $basePath := .Values.collector.basePath -}}
{{- if $useNetworkingV1 }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "jaeger.collector.name" . }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
  {{- if .Values.collector.ingress.annotations }}
  annotations:
    {{- toYaml .Values.collector.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.collector.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $basePath }}
            {{- if $useNetworkingV1 }}
            pathType: ImplementationSpecific
            backend:
              service:
               name: {{ template "jaeger.collector.name" $ }}
               port:
                 number: {{ $servicePort }}
            {{- else }}
            backend:
              serviceName: {{ template "jaeger.collector.name" $ }}
              servicePort: {{ $servicePort }}
            {{- end }}
    {{- end -}}
  {{- if .Values.collector.ingress.tls }}
  tls:
    {{- toYaml .Values.collector.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}
